parameters:
  - name: appComponents
    displayName: "Component name"
    type: string  # Change type to string to allow conditional checks

stages:
  - stage: Test_${{ replace(parameters.appComponents, '-', '_') }}
    dependsOn: Build
    displayName: Test for ${{ parameters.appComponents }}

    # Check if there is an agent with the required capability
    condition: |
      exists('Agent.Capabilities.${{ parameters.appComponents }}')

    pool:
      name: LisaTestAgentPools
      demands:
        - ${{ parameters.appComponents }}

    jobs:
      - job:
        steps:
        - bash: |
            # Write your commands here            
            echo "Hello world"
            echo "i am here"